/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AboutFrame.java
 *
 * Created on 08.01.2011, 19:17:46
 */
package lostfilmnews;

import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.event.WindowFocusListener;
import java.awt.image.BufferedImage;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Влад
 */
public class AboutFrame extends javax.swing.JDialog {

    private static BufferedImage lostfilm_img = null;
    
    private MainFrame frame = null;

    
    /** Creates new form AboutFrame */
    public AboutFrame(MainFrame frame) {
        
        this.frame = frame;
        frame.setEnabled(false);
        initComponents();
        if (lostfilm_img == null) {
            loadImage();
        }
        setIconImage(frame.getIconImage());
        versionLabel.setText("Версия: " + MainFrame.version);

        this.setLocation((Toolkit.getDefaultToolkit().getScreenSize().width - this.getWidth()) / 2,
                (Toolkit.getDefaultToolkit().getScreenSize().height - this.getHeight()) / 2);
        setVisible(true);
    }


    private static void loadImage() {
        try {
            URL iconurl = AboutFrame.class.getResource("/data/losttv.gif");
            lostfilm_img = ImageIO.read(iconurl.openStream());
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            MainFrame.log(ex);
        }
    }
    @Override
    public void paintAll(Graphics g) {
        super.paintAll(g);
    }
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        getGraphics().drawImage(lostfilm_img, 0, 20, null);
    }
    
    


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        versionLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        versionLabel.setText("Version");

        jLabel1.setText("Автор: Полянский Владислав");

        jLabel2.setText("Все предложения на lostfilmnews@yandex.ru");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(versionLabel)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(versionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        for (WindowFocusListener wfl : frame.getWindowFocusListeners()) {
            frame.removeWindowFocusListener(wfl);
        }
        frame.setEnabled(true);
        frame.setVisible(true);
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables

}
